[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18" # Adjust to match your Node.js version if needed

# Configure Netlify dev command
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 4321 # Astro's default port

# Redirect all requests to index.html for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200